---
title: 'Design: Qualitative Criterion'
author: "Kai Gu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reference

> Statistical Guidance on Reporting Results from Studies Evaluating Diagnostic Tests -- Guidance for Industry and FDA Staff, 2007

### With Reference/Gold Standard

Sensitivity and specificity are basic measures of performance for a diagnostic test. Together, they describe how well a test can determine whether a specific condition is present or absent. They each provide distinct and equally important information, and FDA recommends they be presented together:

- Sensitivity refers to how often the test is positive when the condition of
interest is present
- Specificity refers to how often the test is negative when the condition of
interest is absent.

### Without Reference/Gold Standard

When a new test is evaluated by comparison to a non-reference standard, it is impossible to calculate unbiased estimates of sensitivity and specificity. In addition, quantities such as positive predictive value, negative predictive value, and the positive and negative likelihood ratios cannot be computed since the subjects’ condition status (as determined by a reference standard) is unknown.

FDA recommends the use of the terms positive percent agreement and negative percent agreement with the non-reference standard to describe these results.



